#!/bin/bash

set -e

DISTRIBUTION_ZIP=jboss-bpmsuite-7.0.0.Alpha01-engine.zip
DISTRIBUTION_ROUTER_PATH=jboss-bpmsuite-7.0-engine/${KIE_ROUTER_DISTRIBUTION_ARTIFACT}

SOURCES_DIR=/tmp/artifacts
ROUTER_DIR=/opt/${JBOSS_PRODUCT}
SCRIPT_DIR=$(dirname $0)

unzip -q ${SOURCES_DIR}/${DISTRIBUTION_ZIP} -d ${SOURCES_DIR}
mkdir -p ${ROUTER_DIR}
cp -f ${SOURCES_DIR}/${DISTRIBUTION_ROUTER_PATH} ${ROUTER_DIR}
cp -f ${SCRIPT_DIR}/start ${ROUTER_DIR}

chown -R jboss:root ${ROUTER_DIR}
chmod -R ug+x ${ROUTER_DIR}
