#!/bin/bash

ROUTER_OPTS="-Dorg.kie.server.router.host=${KIE_ROUTER_HOST} \
            -Dorg.kie.server.router.port=${KIE_ROUTER_PORT}"

if [ "$KIE_ROUTER_URL_EXTERNAL" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.router.url.external=${KIE_ROUTER_URL_EXTERNAL}"
fi

if [ "$KIE_ROUTER_ID" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.router.id=${KIE_ROUTER_ID}"
fi

if [ "$KIE_ROUTER_NAME" != "" ]; then
    # Need to replace whitespaces with something different from space or escaped space (\ ) characters
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.router.name=${KIE_ROUTER_NAME// /_}"
fi

if [ "$KIE_ROUTER_CONTROLLER_URL" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.controller=${KIE_ROUTER_CONTROLLER_URL}"
fi

if [ "$KIE_ROUTER_CONTROLLER_USER" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.controller.user=${KIE_ROUTER_CONTROLLER_USER}"
fi

if [ "$KIE_ROUTER_CONTROLLER_PASSWORD" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.controller.pwd=${KIE_ROUTER_CONTROLLER_PASSWORD}"
fi

if [ "$KIE_ROUTER_CONTROLLER_TOKEN" != "" ]; then
    ROUTER_OPTS="$ROUTER_OPTS -Dorg.kie.server.controller.token=${KIE_ROUTER_CONTROLLER_TOKEN}"
fi

exec ${JAVA_HOME}/bin/java ${ROUTER_OPTS} \
    -jar /opt/${JBOSS_PRODUCT}/${KIE_ROUTER_DISTRIBUTION_ARTIFACT}
