#!/bin/bash

set -e

SOURCES_DIR=/tmp/artifacts

unzip ${SOURCES_DIR}/jboss-bpmsuite-7.0.0-business-central-monitoring-eap7.zip -d ${SOURCES_DIR}
chmod 0755 ${SOURCES_DIR}/jboss-eap-7.0

cp -rf ${SOURCES_DIR}/jboss-eap-7.0/* ${JBOSS_HOME}/
mv "${JBOSS_HOME}/standalone/deployments/business-central-monitoring.war" "${JBOSS_HOME}/standalone/deployments/ROOT.war"
mv "${JBOSS_HOME}/standalone/deployments/business-central-monitoring.war.dodeploy" "${JBOSS_HOME}/standalone/deployments/ROOT.war.dodeploy"

chown -R jboss:root ${JBOSS_HOME}
chmod 0755 ${JBOSS_HOME}
chmod -R g+rwX ${JBOSS_HOME}
